const images = {
  booking: "/assets/icons/booking.svg",
  dashboard: "/assets/icons/dashboard.svg",
  earning: "/assets/icons/earning.svg",
  notification: "/assets/icons/notification.svg",
  rating: "/assets/icons/rating.svg",
  riderManagement: "/assets/icons/rider_managment.svg",
  setting: "/assets/icons/setting.svg",
  statement: "/assets/icons/statement.svg",
  support: "/assets/icons/support.svg",
  tracking: "/assets/icons/tracking.svg",
  userManagement: "/assets/icons/user_management.svg",
  user: "/assets/icons/user.svg",
  rider: "/assets/icons/rider.svg",
  activate: "/assets/icons/activate.svg",
  deactivate: "/assets/icons/deactivate.svg",
  revenue: "/assets/icons/revenue.svg",
  delivery: "/assets/icons/delivery.svg",
  schedule: "/assets/icons/schedule.svg",
  completed: '/assets/icons/completed.svg',
  admin: "/assets/images/admin.png",
  signal: "/assets/icons/signal.png",
  ProfileNotifcation : '/assets/icons/notification.png',
  profileBell : '/assets/icons/edit.png',
  del : '/assets/icons/del.png',
  warning : '/assets/icons/Warning.png',
  delBlack : '/assets/icons/delBlack.png',
  editBlack : '/assets/icons/editBlack.png',
  transactions : '/assets/icons/transactions.svg',
  paginationLeft : '/assets/paginationLeft.png',
  paginationRight : '/assets/paginationRight.png',
};

export default images;
